FROM python:3.12.7-bookworm

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY . .

RUN python3 -m venv venv
RUN venv/bin/pip install --upgrade pip
RUN venv/bin/pip install -r requirements.txt
RUN venv/bin/alembic upgrade head

CMD ["venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]