version: "3.8"

services:
  web_server_1:
    container_name: web1
    build:
      context: ${WEB_WORKDIR}
      dockerfile: dockerfile
    ports:
      - ${WEB_BINDING_PORT_1}:${WEB_PORT}
    volumes:
      - ${WEB_WORKDIR}:/app
    networks:
      - web_bridge
    restart: always
  web_server_2:
    container_name: web2
    build:
      context: ${WEB_WORKDIR}
      dockerfile: dockerfile
    ports:
      - ${WEB_BINDING_PORT_2}:${WEB_PORT}
    volumes:
      - ${WEB_WORKDIR}:/app
    networks:
      - web_bridge
    restart: always
  web_server_3:
    container_name: web3
    build:
      context: ${WEB_WORKDIR}
      dockerfile: dockerfile
    ports:
      - ${WEB_BINDING_PORT_3}:${WEB_PORT}
    volumes:
      - ${WEB_WORKDIR}:/app
    networks:
      - web_bridge
    restart: always

networks:
  web_bridge:
    external: true