"""empty message

Revision ID: 8eea506189a2
Revises: 
Create Date: 2024-10-28 20:12:11.868779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eea506189a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortUrl', sa.String(), nullable=False),
    sa.Column('longUrl', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_url')),
    sa.UniqueConstraint('longUrl', name=op.f('uq_url_longUrl')),
    sa.UniqueConstraint('shortUrl', name=op.f('uq_url_shortUrl'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###
