version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_DEFAULT_CONFIG_FILE}:/etc/nginx/nginx.conf
    networks:
      - nginx_bridge
    restart: always

networks:
  nginx_bridge:
    external: true