version: "3.8"

services:
  db_ha:
    container_name: postgres
    image: postgres:latest
    ports:
      - ${POSTGRES_BINDING_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - pg_bridge

networks:
  pg_bridge:
    external: true